SELECT * FROM(
	SELECT
	AH_IDNR AS ID,
	AH_CLIENT AS CLIENT_ID,
	AH_NAME AS NAME,
	AH_OTYPE AS TYPE,
	AH_TIMESTAMP2 AS START_TIME,
	AH_TIMESTAMP4 AS END_TIME,
	AH_HOSTDST AS HOST_DESTINATION,
	AH_HOSTSRC AS HOST_SOURCE,
	AH_RUNTIME AS DURATION_SECONDS,
	AH_STATUS AS STATUS_CODE,
	ROW_NUMBER() OVER (PARTITION BY AH_NAME ORDER BY AH_IDNR DESC) AS RANKING,
	'ISSUE' as STATUS
	FROM UC4.AH
	LEFT JOIN UC4.EH
    ON AH.AH_NAME = EH.EH_NAME
	WHERE AH_CLIENT = ?
	AND AH_STATUS BETWEEN 1800 AND 1899
	AND AH_TIMESTAMP4 > CURRENT_DATE-(? / 24)
	AND AH_OTYPE = 'JOBP'
	AND AH_NAME LIKE ?
	ORDER BY AH_IDNR DESC
) WHERE RANKING = 1 ORDER BY NAME
