SELECT D.NAME AS DASHBOARD_NAME, W.TITLE AS TITLE, W.JSON_SETTINGS AS JSON_SETTINGS
FROM CFW_DASHBOARD_WIDGET W 
JOIN CFW_DASHBOARD D
ON W.FK_ID_DASHBOARD = D.PK_ID
WHERE W.TYPE LIKE 'emp_prometheus_%' 
AND  W.JSON_SETTINGS LIKE  ?
OR  W.TITLE LIKE  ?  
LIMIT ?